externalIP: 192.168.9.17
#191.101.192.72
#192.168.9.17
#externalIP: 203.209.80.13
#loadBalancerIP: 192.168.9.17
dashboard:
  enabled: true
  domain: traefik.kube.a-copy.live
ssl:
  enabled: true
#  enforced: true
#  permanentRedirect: true
  insecureSkipVerify: true
acme:
  enabled: true
  email: admin@floretos.com
  logging: true
  onHostRule: true
  staging: false
  persistence:
    enabled: false
kubernetes:
  namespaces:
    - default
    - kube-system
    - tinyfam
rbac:
  enabled: true
persistence:
  enabled: false
#  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 250Mi
  storageClass: "nfs-client"
  path: /data
  annotations: {}
  # subPath: "" # only mount a subpath of the Volume into the pod


