#externalIP: E1C915CB13B4BD79CCC0ECE33518FA87.gr7.ap-southeast-1.eks.amazonaws.com
#externalIP: 203.209.80.13
loadBalancerIP: E1C915CB13B4BD79CCC0ECE33518FA87.gr7.ap-southeast-1.eks.amazonaws.com
dashboard:
  enabled: true
  domain: traefik.aws.cluster.floretos.com
ssl:
  enabled: true
  enforced: true
  permanentRedirect: true
  insecureSkipVerify: true
acme:
  enabled: true
  email: admin@floretos.com
  logging: true
  onHostRule: true
  staging: false
  persistence:
    enabled: false
rbac:
  enabled: true
metrics:
  prometheus:
    enabled: true
