
# kubetpl:syntax:go-template

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .NAME }}-configmap
data:
  NAME: tinyfam
  default.conf: |
    server {
      server_name localhost;

      root /var/www/public;
      index index.php index.html index.htm;

      access_log /var/log/nginx/back-access.log;
      error_log /var/log/nginx/back-error.log;

      location / {
          autoindex on;
          rewrite ^/$ /public/ break;
          rewrite ^(.*)$ /public/$1 break;
          try_files $uri $uri/ /index.php?$query_string;
      }

      # PHP-FPM Configuration Nginx
      location ~ \.php$ {
          try_files $uri = 404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass tinyfam-app-staging-svc:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param REQUEST_URI $request_uri;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
