apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: my-nginx
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: webssl
    port: 443
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hello.staging.kube.floret.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: web
